name: Lint
on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 19
                  cache: "pnpm"

            - run: pnpm install --frozen-lockfile
            - run: pnpm lint
